const express =    require('express');
const router = express.Router();
const editorialController = require('../controllers/editorialController');
const {isLoggedIn,isNotLoogedin,validateAccesousUsuario} = require('../lib/auth');
router.get('/',isLoggedIn, validateAccesousUsuario,editorialController.index);
router.post('/save', isLoggedIn, validateAccesousUsuario,editorialController.save);
router.post('/update',isLoggedIn, validateAccesousUsuario, editorialController.update);
router.post('/delete', isLoggedIn, validateAccesousUsuario,editorialController.delete);
router.get('/findAll',isLoggedIn, validateAccesousUsuario, editorialController.findAll);
router.get('/:id',isLoggedIn, validateAccesousUsuario, editorialController.findById);
module.exports = router;